# syntax=docker/dockerfile:1

FROM python:3.8-alpine3.10

WORKDIR /app

COPY requirements.txt ./

RUN pip install -r --no-cache-dir requirements.txt

COPY . .

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]

