---
# -- (Optional) When using a custom network
# networks:
#   your-traefik-network:
#     external: true
version: '2'
services:
  traefik:
    image: docker.io/library/traefik:v3.0.0
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      # -- (Optional) Enable Dashboard, don't do in production
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/lperalta/docker-prod/Traefik2/config/traefik.yml:/etc/traefik/traefik.yml:ro
    #  - /opt/Traefik2/config/tls.yml:/etc/traefik/tls.yml:ro
      - /home/lperalta/docker-prod/Traefik2/config/ssl/:/etc/traefik/conf/ssl/
    #  - /opt/Traefik/config/certs/acme.json:/etc/traefik/certs/acme.json
    # -- (Optional) When using Cloudflare as Cert Resolver
    # environment:
    #   - CF_DNS_API_TOKEN=your-cloudflare-api-token
    # -- (Optional) When using a custom network
    # networks:
    #   - your-traefik-network
    networks:
      - traefik-test_default
    restart: unless-stopped

networks:
  traefik-test_default:
    external: true
