---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Developer DPyST:
    - Github:
        - icon: github-light.png
          #abbr: GH
          href: https://github.com/dpyst-garrahan
          description: DPyST GitHUB repo

# - Social:
#     - Reddit:
#         - abbr: RE
#           href: https://reddit.com/

# - Entertainment:
#     - YouTube:
#         - abbr: YT
#           href: https://youtube.com/
