---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- resources:
    cpu: true
    memory: true
    disk: /

# - search:
#     provider: duckduckgo
#     target: _blank

- greeting:
    text_size: xl
    text: Servicios


- datetime:
    text_size: xl
    format:
      timeStyle: short
